Repository WDTT-CodingClub/NBDream-Server, pull requests merged in 2024-06, with the labels that each got.

#3 Feat: 엔티티 설계 및 매핑, 패키지 구조 정의
  src/main/java/nbdream/bulletin/domain/Bookmark.java
  src/main/java/nbdream/bulletin/domain/Bulletin.java
  src/main/java/nbdream/bulletin/domain/BulletinCategory.java
  src/main/java/nbdream/bulletin/repository/BookmarkRepository.java
  src/main/java/nbdream/bulletin/repository/BulletinRepository.java
  src/main/java/nbdream/comment/domain/Comment.java
  src/main/java/nbdream/comment/repository/CommentRepository.java
  src/main/java/nbdream/common/domain/BaseEntity.java
  src/main/java/nbdream/common/domain/Status.java
  src/main/java/nbdream/farm/domain/Crop.java
  src/main/java/nbdream/farm/domain/Farm.java
  src/main/java/nbdream/farm/domain/FarmCrop.java
  src/main/java/nbdream/farm/domain/FarmingDiary.java
  src/main/java/nbdream/farm/domain/LandElements.java
  src/main/java/nbdream/farm/domain/Location.java
  src/main/java/nbdream/farm/domain/Schedule.java
  src/main/java/nbdream/farm/domain/Work.java
  src/main/java/nbdream/farm/domain/WorkCategory.java
  src/main/java/nbdream/farm/repository/CropRepository.java
  src/main/java/nbdream/farm/repository/FarmCropRepository.java
  src/main/java/nbdream/farm/repository/FarmRepository.java
  src/main/java/nbdream/farm/repository/FarmingDiaryRepository.java
  src/main/java/nbdream/farm/repository/LandElementsRepository.java
  src/main/java/nbdream/farm/repository/ScheduleRepository.java
  src/main/java/nbdream/farm/repository/WorkRepository.java
  src/main/java/nbdream/image/domain/Image.java
  src/main/java/nbdream/image/repository/ImageRepository.java
  src/main/java/nbdream/ledger/domain/Ledger.java
  src/main/java/nbdream/ledger/domain/LedgerCategory.java
  src/main/java/nbdream/ledger/domain/LedgerHistory.java
  src/main/java/nbdream/ledger/domain/TransactionType.java
  src/main/java/nbdream/ledger/repository/LedgerHistoryRepository.java
  src/main/java/nbdream/ledger/repository/LedgerRepository.java
  src/main/java/nbdream/member/domain/Authority.java
  src/main/java/nbdream/member/domain/LoginType.java
  src/main/java/nbdream/member/domain/Member.java
  src/main/java/nbdream/member/repository/MemberRepository.java
Labels: ✨ feat, 🖥 server

#16 [PR] Git ignore 업데이트
  .gitignore
Labels: 🖥 server, ⚙️ setting

#18 Feat: JWT 인증/인가 구현, 전역 에러 처리 및 공통 응답 정의, 소셜 로그인 구현
  build.gradle
  src/main/java/nbdream/auth/application/AuthService.java
  src/main/java/nbdream/auth/config/AuthConfig.java
  src/main/java/nbdream/auth/config/AuthenticatedMemberId.java
  src/main/java/nbdream/auth/config/AuthenticationExtractor.java
  src/main/java/nbdream/auth/dto/response/OAuthUserProfile.java
  src/main/java/nbdream/auth/dto/response/TokenResponse.java
  src/main/java/nbdream/auth/exception/ExpiredTokenException.java
  src/main/java/nbdream/auth/exception/InvalidProviderException.java
  src/main/java/nbdream/auth/exception/InvalidTokenException.java
  src/main/java/nbdream/auth/infrastructure/JwtTokenProvider.java
  src/main/java/nbdream/auth/infrastructure/OAuthAttributes.java
  src/main/java/nbdream/auth/infrastructure/OAuthProvider.java
  src/main/java/nbdream/auth/presentation/AuthController.java
  src/main/java/nbdream/auth/presentation/interceptor/AuthenticatedMemberResolver.java
  src/main/java/nbdream/auth/presentation/interceptor/AuthenticationInterceptor.java
  src/main/java/nbdream/bulletin/domain/Bookmark.java
  src/main/java/nbdream/bulletin/domain/Bulletin.java
  src/main/java/nbdream/comment/domain/Comment.java
  src/main/java/nbdream/common/advice/CommonControllerAdvice.java
  src/main/java/nbdream/common/advice/response/ApiResponse.java
  src/main/java/nbdream/common/entity/BaseEntity.java
  src/main/java/nbdream/common/entity/Status.java
  src/main/java/nbdream/common/exception/BadRequestException.java
  src/main/java/nbdream/common/exception/InvalidFormatException.java
  src/main/java/nbdream/common/exception/NotFoundException.java
  src/main/java/nbdream/common/exception/UnauthorizedException.java
  src/main/java/nbdream/farm/domain/Crop.java
  src/main/java/nbdream/farm/domain/Farm.java
  src/main/java/nbdream/farm/domain/FarmCrop.java
  src/main/java/nbdream/farm/domain/FarmingDiary.java
  src/main/java/nbdream/farm/domain/LandElements.java
  src/main/java/nbdream/farm/domain/Schedule.java
  src/main/java/nbdream/farm/domain/Work.java
  src/main/java/nbdream/image/domain/Image.java
  src/main/java/nbdream/ledger/domain/Ledger.java
  src/main/java/nbdream/ledger/domain/LedgerHistory.java
  src/main/java/nbdream/member/domain/LoginType.java
  src/main/java/nbdream/member/domain/Member.java
  src/main/java/nbdream/member/repository/MemberRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ feat, 🖥 server, ⚙️ setting

#24 Feat: 내 장부 조회
  .gitignore
  src/main/java/nbdream/accountBook/controller/AccountBookController.java
  src/main/java/nbdream/accountBook/domain/AccountBook.java
  src/main/java/nbdream/accountBook/domain/AccountBookCategory.java
  src/main/java/nbdream/accountBook/domain/AccountBookHistory.java
  src/main/java/nbdream/accountBook/domain/Sort.java
  src/main/java/nbdream/accountBook/domain/TransactionType.java
  src/main/java/nbdream/accountBook/exception/CategoryNotFoundException.java
  src/main/java/nbdream/accountBook/exception/SortTypeNotFoundException.java
  src/main/java/nbdream/accountBook/exception/TransactionTypeNotFoundException.java
  src/main/java/nbdream/accountBook/repository/AccountBookHistoryRepository.java
  src/main/java/nbdream/accountBook/repository/AccountBookRepository.java
  src/main/java/nbdream/accountBook/repository/specifications/AccountBookHistorySpecifications.java
  src/main/java/nbdream/accountBook/service/AccountBookHistoryService.java
  src/main/java/nbdream/accountBook/service/AccountBookService.java
  src/main/java/nbdream/accountBook/service/dto/GetAccountBookListReqDto.java
  src/main/java/nbdream/accountBook/service/dto/GetAccountBookListResDto.java
  src/main/java/nbdream/accountBook/service/dto/GetAccountBookResDto.java
  src/main/java/nbdream/image/repository/ImageRepository.java
  src/main/java/nbdream/ledger/domain/Ledger.java
  src/main/java/nbdream/ledger/domain/LedgerCategory.java
  src/main/java/nbdream/ledger/domain/LedgerHistory.java
  src/main/java/nbdream/ledger/domain/TransactionType.java
  src/main/java/nbdream/ledger/repository/LedgerHistoryRepository.java
  src/main/java/nbdream/ledger/repository/LedgerRepository.java
  src/main/java/nbdream/member/exception/MemberNotFoundException.java
Labels: ✨ feat, 🖥 server

#39 Fix : 페이징 수정
  src/main/java/nbdream/accountBook/repository/AccountBookHistoryRepositoryCustomImpl.java
  src/main/java/nbdream/accountBook/service/AccountBookService.java
  src/main/java/nbdream/accountBook/service/dto/GetAccountBookListReqDto.java
Labels: 🐞 bug, 🖥 server

#42 Fix : 장부 내역 조회 #14
  src/main/java/nbdream/accountBook/controller/AccountBookController.java
  src/main/java/nbdream/accountBook/repository/AccountBookHistoryRepository.java
  src/main/java/nbdream/accountBook/repository/AccountBookHistoryRepositoryCustom.java
  src/main/java/nbdream/accountBook/repository/AccountBookHistoryRepositoryCustomImpl.java
  src/main/java/nbdream/accountBook/repository/specifications/AccountBookHistorySpecifications.java
  src/main/java/nbdream/accountBook/service/AccountBookService.java
  src/main/java/nbdream/accountBook/service/dto/GetAccountBookListReqDto.java
  src/main/java/nbdream/accountBook/service/dto/GetAccountBookListResDto.java
Labels: 🐞 bug, 🛠️ refactor, 🖥 server

#46 Feat : 토양 검정 OpenAPI, AI채팅 OpenAPI
  .github/workflows/cicd.yml
  build.gradle
  src/main/java/nbdream/common/config/GeminiRestTemplateConfig.java
  src/main/java/nbdream/farm/controller/LandElementsController.java
  src/main/java/nbdream/farm/domain/Farm.java
  src/main/java/nbdream/farm/domain/LandElements.java
  src/main/java/nbdream/farm/domain/Location.java
  src/main/java/nbdream/farm/exception/FarmNotFoundException.java
  src/main/java/nbdream/farm/exception/FetchApiInternalServerErrorException.java
  src/main/java/nbdream/farm/exception/LandElementsNotFoundException.java
  src/main/java/nbdream/farm/exception/ParsingInternalServerErrorException.java
  src/main/java/nbdream/farm/exception/PnuNotFoundException.java
  src/main/java/nbdream/farm/repository/FarmRepository.java
  src/main/java/nbdream/farm/service/GeminiService.java
  src/main/java/nbdream/farm/service/LandElementsService.java
  src/main/java/nbdream/farm/service/dto/LandElements/Body.java
  src/main/java/nbdream/farm/service/dto/LandElements/GetLandElementResDto.java
  src/main/java/nbdream/farm/service/dto/LandElements/Item.java
  src/main/java/nbdream/farm/service/dto/LandElements/SoilDataResponse.java
  src/main/java/nbdream/farm/service/dto/gemini/ChatRequest.java
  src/main/java/nbdream/farm/service/dto/gemini/ChatResponse.java
  src/main/java/nbdream/farm/service/dto/gemini/PostAiChatReqDto.java
  src/main/java/nbdream/farm/service/dto/gemini/PostAiChatResDto.java
  src/main/java/nbdream/image/exception/ImageNotFoundException.java
  src/main/resources/application.yml
Labels: ✨ feat, 🖥 server

#47 Fix : 스웨거에 날짜 형식 표기, id값 Long타입으로 변경
  src/main/java/nbdream/accountBook/controller/AccountBookController.java
  src/main/java/nbdream/accountBook/service/AccountBookHistoryService.java
  src/main/java/nbdream/accountBook/service/AccountBookService.java
  src/main/java/nbdream/accountBook/service/dto/GetAccountBookDetailResDto.java
  src/main/java/nbdream/accountBook/service/dto/GetAccountBookResDto.java
Labels: 🐞 bug, 🖥 server

#51 Feat : 농작업일정 OpenAPI 도메인 설계 및 농작업일정 데이터 저장 기능 구현
  src/main/java/nbdream/farm/controller/FarmWorkScheduleController.java
  src/main/java/nbdream/farm/controller/ScheduleController.java
  src/main/java/nbdream/farm/domain/Crop.java
  src/main/java/nbdream/farm/domain/FarmWorkSchedule.java
  src/main/java/nbdream/farm/exception/CreateURLInternalServerErrorException.java
  src/main/java/nbdream/farm/exception/CropNotFoundException.java
  src/main/java/nbdream/farm/exception/FarmWorkScheduleAlreadyExistsException.java
  src/main/java/nbdream/farm/exception/ParsingInternalServerErrorException.java
  src/main/java/nbdream/farm/repository/FarmWorkScheduleRepository.java
  src/main/java/nbdream/farm/service/FarmWorkScheduleService.java
  src/main/java/nbdream/farm/service/ScheduleService.java
  src/main/java/nbdream/farm/service/dto/workSchedule/RequiredCrop.java
  src/main/java/nbdream/farm/service/dto/workSchedule/codeList/Body.java
  src/main/java/nbdream/farm/service/dto/workSchedule/codeList/CodeItem.java
  src/main/java/nbdream/farm/service/dto/workSchedule/codeList/CodeListResponse.java
  src/main/java/nbdream/farm/service/dto/workSchedule/codeList/Items.java
  src/main/java/nbdream/farm/service/dto/workSchedule/detailList/Body.java
  src/main/java/nbdream/farm/service/dto/workSchedule/detailList/DetailItem.java
  src/main/java/nbdream/farm/service/dto/workSchedule/detailList/DetailListResponse.java
  src/main/java/nbdream/farm/service/dto/workSchedule/detailList/Items.java
  src/main/java/nbdream/farm/service/dto/workSchedule/workList/Body.java
  src/main/java/nbdream/farm/service/dto/workSchedule/workList/Items.java
  src/main/java/nbdream/farm/service/dto/workSchedule/workList/WorkItem.java
  src/main/java/nbdream/farm/service/dto/workSchedule/workList/WorkListResponse.java
  src/main/resources/application.yml
Labels: ✨ feat, 🖥 server

#53 Feature : 캘린더) 농작업 일정 조회 기능 구현
  src/main/java/nbdream/farm/controller/ScheduleController.java
  src/main/java/nbdream/farm/exception/CropFromWorkScheduleNotFoundException.java
  src/main/java/nbdream/farm/exception/FarmWorkScheduleNotFoundException.java
  src/main/java/nbdream/farm/repository/FarmWorkScheduleCustomRepository.java
  src/main/java/nbdream/farm/service/ScheduleService.java
  src/main/java/nbdream/farm/service/dto/schedule/request/FarmWorkListReqDto.java
  src/main/java/nbdream/farm/service/dto/schedule/response/FarmWorkListResDto.java
  src/main/java/nbdream/farm/service/dto/schedule/response/FarmWorkResDto.java
Labels: ✨ feat, 🖥 server

#59 Fix : 토양 검정 OpenAPI 로직 변경, 카카오 주소 찾기 API 구현
  src/main/java/nbdream/common/config/AsyncConfig.java
  src/main/java/nbdream/farm/controller/LandElementsController.java
  src/main/java/nbdream/farm/domain/Location.java
  src/main/java/nbdream/farm/exception/AsyncExceptionHandler.java
  src/main/java/nbdream/farm/exception/ClosestSoilDataInternalServerErrorException.java
  src/main/java/nbdream/farm/exception/CoordinatesNotFoundException.java
  src/main/java/nbdream/farm/exception/KakaoLocalServiceErrorException.java
  src/main/java/nbdream/farm/service/GeminiService.java
  src/main/java/nbdream/farm/service/KakaoAddressService.java
  src/main/java/nbdream/farm/service/KakaoAsyncService.java
  src/main/java/nbdream/farm/service/LandElementsService.java
  src/main/java/nbdream/farm/service/dto/LandElements/soilData/Body.java
  src/main/java/nbdream/farm/service/dto/LandElements/soilData/GetLandElementResDto.java
  src/main/java/nbdream/farm/service/dto/LandElements/soilData/Item.java
  src/main/java/nbdream/farm/service/dto/LandElements/soilData/SoilDataResponse.java
  src/main/java/nbdream/farm/service/dto/LandElements/soilDataList/Body.java
  src/main/java/nbdream/farm/service/dto/LandElements/soilDataList/ItemBjd.java
  src/main/java/nbdream/farm/service/dto/LandElements/soilDataList/SoilDataListResponse.java
  src/main/java/nbdream/farm/service/dto/workSchedule/kakaoResponse/KakaoResponse.java
  src/main/java/nbdream/farm/util/Coordinates.java
  src/main/java/nbdream/farm/util/UrlUtil.java
  src/main/resources/application.yml
Labels: 🐞 bug, ✨ feat, 🖥 server

#61 Fix : 프로필 수정 시 토양 검정 데이터 갱신
  src/main/java/nbdream/farm/controller/LandElementsController.java
  src/main/java/nbdream/farm/domain/Farm.java
  src/main/java/nbdream/farm/domain/Location.java
  src/main/java/nbdream/farm/service/GeminiService.java
  src/main/java/nbdream/farm/service/LandElementsService.java
  src/main/java/nbdream/member/dto/request/UpdateProfileReqDto.java
  src/main/java/nbdream/member/service/MyProfileService.java
Labels: 🐞 bug, 🖥 server

#63 Fix : 장부 조회 기능 명세 변경으로 인한 수정
  src/main/java/nbdream/accountBook/repository/AccountBookHistoryRepositoryCustom.java
  src/main/java/nbdream/accountBook/repository/AccountBookHistoryRepositoryCustomImpl.java
  src/main/java/nbdream/accountBook/service/AccountBookService.java
  src/main/java/nbdream/accountBook/service/dto/GetAccountBookGraphResDto.java
  src/main/java/nbdream/accountBook/service/dto/GetAccountBookListResDto.java
Labels: ✨ feat, 🖥 server

#64 Feat : 일정 CRUD
  src/main/java/nbdream/farm/controller/ScheduleController.java
  src/main/java/nbdream/farm/domain/Schedule.java
  src/main/java/nbdream/farm/exception/ScheduleNotFoundException.java
  src/main/java/nbdream/farm/exception/UnEditableScheduleException.java
  src/main/java/nbdream/farm/repository/SearchScheduleRepository.java
  src/main/java/nbdream/farm/service/ScheduleService.java
  src/main/java/nbdream/farm/service/dto/schedule/request/PostScheduleReqDto.java
  src/main/java/nbdream/farm/service/dto/schedule/request/PutScheduleReqDto.java
  src/main/java/nbdream/farm/service/dto/schedule/request/ScheduleListReqDto.java
  src/main/java/nbdream/farm/service/dto/schedule/request/WeekScheduleListReqDto.java
  src/main/java/nbdream/farm/service/dto/schedule/response/FarmWorkListResDto.java
  src/main/java/nbdream/farm/service/dto/schedule/response/ScheduleListResDto.java
  src/main/java/nbdream/farm/service/dto/schedule/response/ScheduleResDto.java
Labels: ✨ feat, 🖥 server

#73 Fix : 일정 상세 조회, 농작업 일정 조회 버그 수정
  src/main/java/nbdream/farm/controller/FarmWorkScheduleController.java
  src/main/java/nbdream/farm/exception/InvalidDateFormatException.java
  src/main/java/nbdream/farm/service/ScheduleService.java
Labels: 🐞 bug, 🔎 test

#74 Fix : 게시글 북마크 카운트 계속 증가하는 버그 수정
  src/main/java/nbdream/bulletin/service/BulletinService.java
Labels: 🐞 bug, 🖥 server

#75 Fix : 게시글 삭제 후 내 코멘트 조회 시 버그 해결
  src/main/java/nbdream/bulletin/service/BulletinService.java
Labels: 🐞 bug, 🖥 server

#76 Fix : 게시글 조회, 댓글 수정 버그
  src/main/java/nbdream/bulletin/exception/CommentNotFoundException.java
  src/main/java/nbdream/comment/domain/Comment.java
  src/main/java/nbdream/comment/service/CommentService.java
  src/main/java/nbdream/member/service/MemberService.java
Labels: 🐞 bug

#77 Fix : 회원 탈퇴 시 Schedule 삭제 추가
  src/main/java/nbdream/farm/repository/ScheduleRepository.java
  src/main/java/nbdream/member/service/MemberService.java
Labels: 🐞 bug
